- name: Deploy Dynamic MOTD
  hosts: all
  become: true

  tasks:
    - name: Copy MOTD file
      template:
        src: "motd.j2 template location"
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
